### PR TITLE
docker compose tweaks

### PR DESCRIPTION
**Pull request by knopki**
Move all reusable service definitions to `.docker/common.yml`.
`compose.yml` rebuild all images and use "dev" versions by default.
Remove compose overrides.

### CODE REVIEW

**Comment by pyoner** [comment]
@knopki it looks good
Did you test it?

**Comment by knopki** [comment]
@pyoner Of course I test it 👀 

Everything is working except `metis-bff` of course. You need to copy example config and initialize db. Config from inside of image not used because of volume. DB init doesn't work because of entrypoint override. "dev build"

**Comment by blokhin** [comment]
@pyoner can I merge?

**Comment by pyoner** [comment]
@knopki I have got an error
```bash
➜  metis-backend git:(tweak-dockerf-compose) docker-compose build --no-cache   
[+] Building 0.0s (2/2) FINISHED                                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 2B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount1419726589/Dockerfile: no such file or directory
```

**Comment by pyoner** [comment]
@knopki got an error for podman
```bash
➜  metis-backend git:(tweak-dockerf-compose) podman-compose build --no-cache
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
Traceback (most recent call last):
  File "/home/pyoner/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/pyoner/.local/lib/python3.10/site-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/home/pyoner/.local/lib/python3.10/site-packages/podman_compose.py", line 1423, in run
    cmd(self, args)
  File "/home/pyoner/.local/lib/python3.10/site-packages/podman_compose.py", line 1754, in wrapped
    return func(*args, **kw)
  File "/home/pyoner/.local/lib/python3.10/site-packages/podman_compose.py", line 1994, in compose_build
    build_one(compose, args, cnt)
  File "/home/pyoner/.local/lib/python3.10/site-packages/podman_compose.py", line 1957, in build_one
    raise OSError("Dockerfile not found in " + ctx)
OSError: Dockerfile not found in .docker/.
```

**Comment by knopki** [comment]
> @knopki I have got an error

`docker compose`'s output is very uninformative.


> @knopki got an error for podman

Working on my machine ©️ (`podman-compose` 1.0.3/1.0.6, `podman` 4.2.0)
This is very strange. There is not even a `podman build ...` in the output. It looks like it can't even build `metis-backend` due to trying to find the `Dockerfile` in `.docker` directory (where is `common.yml`). It's as if it resolves the path in `common.yml` instead of just merging values (as in the compose file specification).
I moved `build.context` definitions to the root `compose.yml`. @pyoner can you try again?

**Comment by pyoner** [comment]
@knopki thank you for the fix!
docker is working now

**Comment by knopki** [comment]
@pyoner New version. `metis-gui` with bind mounts. Should work after merge of: https://github.com/basf/metis-gui/pull/145 and https://github.com/basf/metis-gui/pull/146

**Review by blokhin — APPROVED** [review]

**Pull request merged**
