### PR TITLE
docker compose

### PR DESCRIPTION
**Pull request by pyoner**
feat(compose.dev-bff.yml): add NODE_ENV=development build argument to metis-bff service to enable development mode
refactor(compose.yml): remove rabbitmq service dependency from metis-api service as it is not used in the service

### CODE REVIEW

**Comment by pyoner** [comment]
@blokhin please review the PR

**Comment by blokhin** [comment]
re-addressing to @knopki

**Comment by blokhin** [comment]
@pyoner `rabbitmq` is introduced by AiiDA (temporarily removed now), so as soon as AiiDA comes back, we have to require `rabbitmq` back again

**Comment by pyoner** [comment]
@blokhin ok, I commented out this line

**Review by knopki — APPROVED** [review]

**Pull request merged**
